#!/usr/bin/env bash
# 阿斯拉量化系統 — 安裝 git pre-commit hook
#
# 將 backend/scripts/check_repo_health.py 註冊為 pre-commit hook，
# 每次 git commit 前自動跑「檔案行數 / chart_state / prompt module 檢查」。
#
# 用法：bash backend/scripts/install_git_hooks.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
HOOK_PATH="${REPO_ROOT}/.git/hooks/pre-commit"

if [[ ! -d "${REPO_ROOT}/.git" ]]; then
  echo "✗ 找不到 ${REPO_ROOT}/.git — 此目錄不是 git repo"
  exit 1
fi

cat > "${HOOK_PATH}" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by backend/scripts/install_git_hooks.sh
# 跑 backend/scripts/check_repo_health.py，違反規則會 block commit
set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
HEALTH_CHECK="${REPO_ROOT}/backend/scripts/check_repo_health.py"

if [[ -f "${HEALTH_CHECK}" ]]; then
  python3 "${HEALTH_CHECK}"
fi

EOF

chmod +x "${HOOK_PATH}"

echo "✅ 已安裝 pre-commit hook 至 ${HOOK_PATH}"
echo ""
echo "下次 git commit 前會自動跑 backend/scripts/check_repo_health.py"
echo "若想手動跑：python3 backend/scripts/check_repo_health.py"
echo "若想暫時跳過：git commit --no-verify（不建議常用）"
